<?php

namespace app\models\forms;
use yii\base\Model;

/**
 * Class CopyForm
 */
class CopyForm extends Model
{
    public $flightDate;
    public $clientList;
    public $flight;

    public $report;

    /**
     * @return array
     */
    public function rules()
    {
        return []; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'flightDate' => 'Дата рейса',
            'flight' => 'Рейс',
            'clientList' => 'Клиенты',

        ];
    }

    /**
     * @return bool
     */
    public function copyFiles(): bool
    {
        if ($this->validate()) {
            return true;
        }
        return false;
    }
}
